// Package hook installs and uninstalls the .git/hooks/pre-commit entry.
package hook

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// Mode chooses how install handles an existing hook.
type Mode int

const (
	// ModeAbort refuses to overwrite; returns ExistsError.
	ModeAbort Mode = iota
	// ModeReplace backs up the existing hook and replaces it with prenup.
	ModeReplace
	// ModeChain saves the existing hook as pre-commit.local and invokes it
	// from the prenup-managed wrapper before running prenup.
	ModeChain
	// ModeForce overwrites without backup.
	ModeForce
)

// ExistsError is returned by Install when a non-prenup hook already exists and
// Mode is ModeAbort.
type ExistsError struct{ Path string }

func (e *ExistsError) Error() string {
	return fmt.Sprintf("hook already exists at %s (use --force, --replace, or --chain)", e.Path)
}

// PrenupMarker is written into the managed hook so uninstall can verify
// authorship before removing the file.
const PrenupMarker = "# prenup-managed-hook"

// Install writes a pre-commit hook at repoRoot/.git/hooks/pre-commit that
// invokes the prenup binary found at binaryPath. mode controls collision
// handling.
func Install(repoRoot, binaryPath string, mode Mode) error {
	hookPath := filepath.Join(repoRoot, ".git", "hooks", "pre-commit")

	// Git hooks live in .git/hooks (already restrictive, owned by the user).
	// 0o750 satisfies gosec G301 while remaining traversable for the user.
	if err := os.MkdirAll(filepath.Dir(hookPath), 0o750); err != nil {
		return fmt.Errorf("ensuring hooks dir: %w", err)
	}

	// hookPath is constructed from the validated repoRoot plus a fixed suffix.
	existing, err := os.ReadFile(hookPath) //nolint:gosec // G304: hookPath is a constructed path under .git/hooks.
	if err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("reading existing hook: %w", err)
	}

	existedAndManaged := len(existing) > 0 && strings.Contains(string(existing), PrenupMarker)

	switch {
	case len(existing) == 0 || existedAndManaged:
		// Clear to write.
	case mode == ModeAbort:
		return &ExistsError{Path: hookPath}
	case mode == ModeReplace:
		backup := hookPath + ".prenup-backup"
		if err := os.Rename(hookPath, backup); err != nil {
			return fmt.Errorf("backing up existing hook: %w", err)
		}
	case mode == ModeChain:
		localPath := filepath.Join(repoRoot, ".git", "hooks", "pre-commit.local")
		if err := os.Rename(hookPath, localPath); err != nil {
			return fmt.Errorf("saving existing hook as pre-commit.local: %w", err)
		}
		// Hooks must be executable; chmod ensures the owner+group can run it.
		if err := os.Chmod(localPath, 0o750); err != nil { //nolint:gosec // G302: git hooks must be executable.
			return fmt.Errorf("chmod pre-commit.local: %w", err)
		}
	case mode == ModeForce:
		// Overwrite without backup.
	}

	script := generateScript(binaryPath, mode == ModeChain)
	// Git requires the hook to be executable; the owner+group can run it.
	if err := os.WriteFile(hookPath, []byte(script), 0o750); err != nil { //nolint:gosec // G306: git hooks must be executable.
		return fmt.Errorf("writing hook: %w", err)
	}
	return nil
}

// generateScript returns the shell script body for the managed hook.
//
// `set -e` is intentional: if the chained pre-commit.local exits non-zero we
// want to fail-closed and block the commit before prenup even starts. The
// recorded prenup binary path is invoked with "$@" so any future Git hooks
// that do receive arguments forward them; today Git invokes pre-commit with
// none, so this is forward-compatible polish only.
func generateScript(binaryPath string, chain bool) string {
	var b strings.Builder
	b.WriteString("#!/usr/bin/env bash\n")
	b.WriteString(PrenupMarker + "\n")
	b.WriteString("# Do not edit this file by hand; regenerate via `prenup install`.\n")
	b.WriteString("set -e\n")
	if chain {
		b.WriteString(`LOCAL="$(dirname "$0")/pre-commit.local"` + "\n")
		// fail-closed: a failing local hook aborts the script before exec.
		b.WriteString(`if [ -x "$LOCAL" ]; then "$LOCAL" "$@"; fi` + "\n")
	}
	fmt.Fprintf(&b, "exec %q \"$@\"\n", binaryPath)
	return b.String()
}

// Uninstall removes the managed hook at repoRoot. If a .prenup-backup exists,
// it is restored; otherwise the hook is simply deleted. Returns nil if no
// managed hook is installed.
func Uninstall(repoRoot string) error {
	hookPath := filepath.Join(repoRoot, ".git", "hooks", "pre-commit")
	data, err := os.ReadFile(hookPath) //nolint:gosec // G304: hookPath is constructed under .git/hooks.
	if os.IsNotExist(err) {
		return nil
	}
	if err != nil {
		return fmt.Errorf("reading hook: %w", err)
	}
	if !strings.Contains(string(data), PrenupMarker) {
		return fmt.Errorf("hook at %s was not installed by prenup; leaving it alone", hookPath)
	}

	backup := hookPath + ".prenup-backup"
	if _, err := os.Stat(backup); err == nil {
		if err := os.Rename(backup, hookPath); err != nil {
			return fmt.Errorf("restoring backup: %w", err)
		}
		return nil
	}
	localPath := filepath.Join(repoRoot, ".git", "hooks", "pre-commit.local")
	if _, err := os.Stat(localPath); err == nil {
		if err := os.Rename(localPath, hookPath); err != nil {
			return fmt.Errorf("restoring chained pre-commit.local: %w", err)
		}
		return nil
	}
	return os.Remove(hookPath)
}
