// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/c2fo/prenup/internal/runner"
	mock "github.com/stretchr/testify/mock"
)

// NewSink creates a new instance of Sink. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSink(t interface {
	mock.TestingT
	Cleanup(func())
}) *Sink {
	mock := &Sink{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Sink is an autogenerated mock type for the Sink type
type Sink struct {
	mock.Mock
}

type Sink_Expecter struct {
	mock *mock.Mock
}

func (_m *Sink) EXPECT() *Sink_Expecter {
	return &Sink_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type Sink
func (_mock *Sink) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Sink_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type Sink_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *Sink_Expecter) Close() *Sink_Close_Call {
	return &Sink_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *Sink_Close_Call) Run(run func()) *Sink_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Sink_Close_Call) Return(err error) *Sink_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Sink_Close_Call) RunAndReturn(run func() error) *Sink_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Emit provides a mock function for the type Sink
func (_mock *Sink) Emit(event runner.Event) {
	_mock.Called(event)
	return
}

// Sink_Emit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Emit'
type Sink_Emit_Call struct {
	*mock.Call
}

// Emit is a helper method to define mock.On call
//   - event runner.Event
func (_e *Sink_Expecter) Emit(event interface{}) *Sink_Emit_Call {
	return &Sink_Emit_Call{Call: _e.mock.On("Emit", event)}
}

func (_c *Sink_Emit_Call) Run(run func(event runner.Event)) *Sink_Emit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 runner.Event
		if args[0] != nil {
			arg0 = args[0].(runner.Event)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Sink_Emit_Call) Return() *Sink_Emit_Call {
	_c.Call.Return()
	return _c
}

func (_c *Sink_Emit_Call) RunAndReturn(run func(event runner.Event)) *Sink_Emit_Call {
	_c.Run(run)
	return _c
}

// NewExecutor creates a new instance of Executor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewExecutor(t interface {
	mock.TestingT
	Cleanup(func())
}) *Executor {
	mock := &Executor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Executor is an autogenerated mock type for the Executor type
type Executor struct {
	mock.Mock
}

type Executor_Expecter struct {
	mock *mock.Mock
}

func (_m *Executor) EXPECT() *Executor_Expecter {
	return &Executor_Expecter{mock: &_m.Mock}
}

// Run provides a mock function for the type Executor
func (_mock *Executor) Run(ctx context.Context, command string, workingDir string, env map[string]string, onLine func(runner.Stream, string)) error {
	ret := _mock.Called(ctx, command, workingDir, env, onLine)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, map[string]string, func(runner.Stream, string)) error); ok {
		r0 = returnFunc(ctx, command, workingDir, env, onLine)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Executor_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type Executor_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - ctx context.Context
//   - command string
//   - workingDir string
//   - env map[string]string
//   - onLine func(runner.Stream, string)
func (_e *Executor_Expecter) Run(ctx interface{}, command interface{}, workingDir interface{}, env interface{}, onLine interface{}) *Executor_Run_Call {
	return &Executor_Run_Call{Call: _e.mock.On("Run", ctx, command, workingDir, env, onLine)}
}

func (_c *Executor_Run_Call) Run(run func(ctx context.Context, command string, workingDir string, env map[string]string, onLine func(runner.Stream, string))) *Executor_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 map[string]string
		if args[3] != nil {
			arg3 = args[3].(map[string]string)
		}
		var arg4 func(runner.Stream, string)
		if args[4] != nil {
			arg4 = args[4].(func(runner.Stream, string))
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *Executor_Run_Call) Return(err error) *Executor_Run_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Executor_Run_Call) RunAndReturn(run func(ctx context.Context, command string, workingDir string, env map[string]string, onLine func(runner.Stream, string)) error) *Executor_Run_Call {
	_c.Call.Return(run)
	return _c
}
